# Exec-only keybindings for OmniWM.
#
# OmniWM's hotkey vocabulary (Core/Input/HotkeyCommand.swift) is window
# management only — there is no exec/spawn action of any kind. Every Hyprland
# binding that shells out therefore lands here instead of in ./hotkeys.nix.
#
# Source of truth is configs/hypr/bindings.lua. Bindings that are Linux-shaped
# (power menu, suspend inhibit, game mode, airplane mode) or already native on
# macOS (media and brightness keys, emoji picker, notification centre, the
# SUPER+C/V/X/A clipboard emulation) are deliberately not carried over — see the
# gap table in OMNI-WM-PROJECT.md.
#
# ⚠️ This uses skhd.zig via ../../pkgs/skhd-zig, NOT home-manager's
# `services.skhd`. That module hardcodes `pkgs.skhd`, whose 0.3.9 release
# segfaults on macOS 26 as soon as any bound chord is pressed. skhd.zig keeps
# the same skhdrc grammar, so the bindings below are unchanged from that attempt.
{
  lib,
  pkgs,
  config,
  ...
}:

with lib;

let

  cfg = config.programs.homenix.omniwm;

  homenixBin = "${config.home.homeDirectory}/.config/homenix/bin";

  configFile = "${config.xdg.configHome}/skhd/skhdrc";

in
{
  options.programs.homenix.omniwm.skhd = {
    enable = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Install skhd.zig with the exec bindings OmniWM cannot express itself
        (launching a terminal, browser, screenshots, and so on).
      '';
    };

    package = mkOption {
      type = types.package;
      default = pkgs.callPackage ../../pkgs/skhd-zig { };
      defaultText = literalExpression "pkgs.callPackage ../../pkgs/skhd-zig { }";
      description = "skhd.zig package to use.";
    };
  };

  config =
    mkIf (config.programs.homenix.enable && cfg.enable && cfg.skhd.enable && pkgs.stdenv.isDarwin)
      {
        # The Hyprland quick-settings menu is reachable on macOS through the same
        # wrapper the AeroSpace module installs.
        home.file.".config/homenix/bin/settings" = {
          source = ../../bin/darwin-settings;
          executable = true;
        };

        home.packages = [ cfg.skhd.package ];

        xdg.configFile."skhd/skhdrc".text = ''
          # Generated by modules/omniwm/skhd.nix -- do not edit by hand.
          #
          # Hyprland SUPER maps to Command throughout, matching ./hotkeys.nix.
          #
          # Note these fire on key repeat, so holding a chord launches repeatedly.
          # That is ordinary hotkey-daemon behaviour, not a misconfiguration.

          # SUPER+RETURN -- terminal (bindings.lua: xdg-terminal-exec)
          cmd - return : open -na Ghostty

          # SUPER+SHIFT+B -- browser (bindings.lua: xdg-open https://)
          cmd + shift - b : open -na "Google Chrome"

          # SUPER+SHIFT+F -- file manager (bindings.lua: xdg-open ~)
          cmd + shift - f : open ~

          # SUPER+SHIFT+E -- quick settings menu (bindings.lua: scripts/settings.sh).
          # The AeroSpace module had this on cmd-ctrl-e, which had drifted from
          # Hyprland; this restores the original chord.
          cmd + shift - e : ${homenixBin}/settings

          # SUPER+SHIFT+S -- interactive area screenshot
          # (bindings.lua: scripts/screenshot.sh --area).
          # The other Hyprland variants (--now / --in5 / --in10 / --active, all on
          # SUPER+Print) are not carried over: Mac keyboards have no Print key, and
          # macOS already binds Cmd+Shift+3/4/5 to the same captures natively.
          cmd + shift - s : screencapture -i "$HOME/Desktop/screenshot-$(date +%Y%m%d-%H%M%S).png"

          # CTRL+ALT+L -- lock screen (bindings.lua: loginctl lock-session)
          ctrl + alt - l : pmset displaysleepnow

          # SUPER+SHIFT+Q -- terminate the focused window's process
          # (bindings.lua: scripts/kill_focus.sh). Goes through the IPC socket,
          # which is why general.ipcEnabled is forced on in ./settings.nix.
          #
          # Every --format, `text` included, emits a header row and all columns
          # regardless of --fields, so the PID is column 2 of the first data row.
          # The regex guard makes this a no-op when nothing is focused.
          cmd + shift - q : pid=$(${getExe cfg.package} query windows --focused --format tsv | awk 'NR>1 && $2 ~ /^[0-9]+$/ { print $2; exit }') && [ -n "$pid" ] && kill -9 "$pid"
        '';

        # Run the executable from inside the .app bundle: skhd needs its bundle
        # identity (com.jackielii.skhd) to keep its Accessibility and Input
        # Monitoring grants. Upstream's own --install-service uses SMAppService,
        # which would fight home-manager over the agent's lifecycle.
        launchd.agents.skhd = {
          enable = true;
          config = {
            ProgramArguments = [
              "${cfg.skhd.package}/Applications/skhd.app/Contents/MacOS/skhd"
              "-c"
              configFile
            ];
            RunAtLoad = true;
            KeepAlive = true;
            StandardOutPath = "${config.home.homeDirectory}/Library/Logs/skhd/skhd.log";
            StandardErrorPath = "${config.home.homeDirectory}/Library/Logs/skhd/skhd.err.log";
          };
        };
      };
}
